### ISSUE TITLE
Ios buy inApp and close App

### ISSUE THREAD

**Issue by developOPQA** [cozycodegh/cordova-plugin-inapppurchases#11]
I am using the latest version of the plugin, but I am having an error when trying to make some strange use case, the problem I am having is that when I buy an InApp, the purchase window appears, but before the purchase message appears confirmed I close the app, with the app closed I see that the confirmed purchase window appears, I open the app again, and I do not see any log referring to that purchase, I execute restorePurchases and it returns an empty object, and if I try to buy the same article, Apple tells me that I already have this article, but the plugin does not give me an error at this point and should give me an error that I already have the article so I can consume it.
Thanks for the plugin.

**Comment by cozycodegh** [comment]
Hi developOPQA,

Apple purchases are consumed and completed in the first call to purchase (unlike Android), so it shouldn’t be a problem for buying more of the same consumable again. 

I wasn’t able to replicate the error, for me there were logs showing the purchase going through after reopening the app from the background.

Sometimes when I try to buy it twice at the same time, Apple tells me the purchase was already bought, and nothing is returned, but it should be okay since it was already returned in the other call.

**Comment by cozycodegh** [comment]
Hello, 
If this didn’t solve the problem re-open the issue again.
